meta_product_name: "Choogle"
meta_title: "Choogle - Vote with your friends the next place to go"
meta_description: "The easiest way to collectively choose a bar, a restaurant, a holiday destination or any other place"
meta_image: "image-meta.png"
twitter_account: "@choogle_xyz"
