meta_product_name: "Choogle"
meta_title: "Choogle - Vote with your friends the next place to go"
meta_description: "Choogle is a simple voting tool to choose with your friends the next place to go"
# meta_image: ""
twitter_account: "@choogle_xyz"